In [1]:
!pip install pymongo pandas

Requirement already satisfied: pymongo in /usr/local/python/3.11.15/lib/python3.11/site-packages (4.16.0)
Requirement already satisfied: pandas in /usr/local/python/3.11.15/lib/python3.11/site-packages (3.0.1)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pymongo) (2.8.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [3]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")

In [4]:
db = client['clinicavet']
colecao = db['atendimentos']

1 - 50 registros na coleção 'atendimentos'.

In [5]:
db.atendimentos.drop()

atendimentos = [
{"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
{"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
{"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
{"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
{"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
{"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
{"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
{"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
{"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
{"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
{"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
{"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
{"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
{"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
{"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

Buscando todos os registros da coleção

In [6]:
colecao.insert_many(atendimentos)

InsertManyResult([ObjectId('69c57acc204d266274b98421'), ObjectId('69c57acc204d266274b98422'), ObjectId('69c57acc204d266274b98423'), ObjectId('69c57acc204d266274b98424'), ObjectId('69c57acc204d266274b98425'), ObjectId('69c57acc204d266274b98426'), ObjectId('69c57acc204d266274b98427'), ObjectId('69c57acc204d266274b98428'), ObjectId('69c57acc204d266274b98429'), ObjectId('69c57acc204d266274b9842a'), ObjectId('69c57acc204d266274b9842b'), ObjectId('69c57acc204d266274b9842c'), ObjectId('69c57acc204d266274b9842d'), ObjectId('69c57acc204d266274b9842e'), ObjectId('69c57acc204d266274b9842f'), ObjectId('69c57acc204d266274b98430'), ObjectId('69c57acc204d266274b98431'), ObjectId('69c57acc204d266274b98432'), ObjectId('69c57acc204d266274b98433'), ObjectId('69c57acc204d266274b98434'), ObjectId('69c57acc204d266274b98435'), ObjectId('69c57acc204d266274b98436'), ObjectId('69c57acc204d266274b98437'), ObjectId('69c57acc204d266274b98438'), ObjectId('69c57acc204d266274b98439'), ObjectId('69c57acc204d266274b9843a'), ObjectId('69c57acc204d266274b9843b'), ObjectId('69c57acc204d266274b9843c'), ObjectId('69c57acc204d266274b9843d'), ObjectId('69c57acc204d266274b9843e'), ObjectId('69c57acc204d266274b9843f'), ObjectId('69c57acc204d266274b98440'), ObjectId('69c57acc204d266274b98441'), ObjectId('69c57acc204d266274b98442'), ObjectId('69c57acc204d266274b98443'), ObjectId('69c57acc204d266274b98444'), ObjectId('69c57acc204d266274b98445'), ObjectId('69c57acc204d266274b98446'), ObjectId('69c57acc204d266274b98447'), ObjectId('69c57acc204d266274b98448'), ObjectId('69c57acc204d266274b98449'), ObjectId('69c57acc204d266274b9844a'), ObjectId('69c57acc204d266274b9844b'), ObjectId('69c57acc204d266274b9844c'), ObjectId('69c57acc204d266274b9844d'), ObjectId('69c57acc204d266274b9844e'), ObjectId('69c57acc204d266274b9844f'), ObjectId('69c57acc204d266274b98450'), ObjectId('69c57acc204d266274b98451'), ObjectId('69c57acc204d266274b98452')], acknowledged=True)

In [7]:
todos_dados = list(colecao.find({}))

In [8]:
df = pd.DataFrame(todos_dados)

In [9]:
print("Colunas disponíveis:", df.columns.tolist())

Colunas disponíveis: ['_id', 'tutor', 'animal', 'nome_pet', 'servico', 'valor', 'cidade', 'data', 'forma_pagamento']

2 - Atendimentos com valor entre 90 e 200 reais.

In [10]:
consulta_valor = list(colecao.find({
    "valor": {"$gte": 90, "$lte": 200}
}))

display(consulta_valor)

[{'_id': ObjectId('69c57acc204d266274b98421'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98422'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98424'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98425'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98426'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98427'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9842a'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9842b'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9842c'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9842d'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b9842e'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98431'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98432'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98433'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98434'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98436'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98438'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9843a'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9843b'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9843e'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9843f'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98440'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98441'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98443'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98444'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98445'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98447'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9844a'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9844b'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b9844c'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9844d'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9844f'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98451'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98452'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

3 - Atendimentos das cidades Assis, Ourinhos, Pompeia e Marília

In [11]:
atendimentos_cidades = list(colecao.find({
    "cidade": {"$in": ["Assis", "Ourinhos", "Pompeia", "Marília"]}
}))

display(atendimentos_cidades)

[{'_id': ObjectId('69c57acc204d266274b98421'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98422'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98423'),
  'tutor': 'Carlos',
  'animal': 'Cachorro',
  'nome_pet': 'Thor3',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98424'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98425'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98426'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98427'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98428'),
  'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98429'),
  'tutor': 'Igor',
  'animal': 'Gato',
  'nome_pet': 'Simba9',
  'servico': 'Banho',
  'valor': 55,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9842a'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9842b'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9842c'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9842d'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b9842e'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9842f'),
  'tutor': 'Rafael',
  'animal': 'Gato',
  'nome_pet': 'Mia15',
  'servico': 'Banho',
  'valor': 65,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98430'),
  'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98431'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98432'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98433'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98434'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98435'),
  'tutor': 'Caio',
  'animal': 'Cachorro',
  'nome_pet': 'Spike21',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98436'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98437'),
  'tutor': 'Elisa',
  'animal': 'Cachorro',
  'nome_pet': 'Mel23',
  'servico': 'Exame',
  'valor': 210,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98438'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98439'),
  'tutor': 'Gisele',
  'animal': 'Gato',
  'nome_pet': 'Nina25',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b9843a'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9843b'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9843c'),
  'tutor': 'Joao',
  'animal': 'Gato',
  'nome_pet': 'Luna28',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b9843d'),
  'tutor': 'Karen',
  'animal': 'Cachorro',
  'nome_pet': 'Thor29',
  'servico': 'Cirurgia',
  'valor': 780,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b9843e'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b9843f'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98440'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98441'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c57acc204d266274b98442'),
  'tutor': 'Paulo',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt34',
  'servico': 'Banho',
  'valor': 75,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98443'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98444'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c57acc204d266274b98445'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c57acc204d266274b98446'),
  'tutor': 'Tiago',
  'animal': 'Gato',
  'nome_pet': 'Lili38',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

4 - DataFrame

In [12]:
df = pd.DataFrame(todos_dados)
df

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69c57acc204d266274b98421,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69c57acc204d266274b98422,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69c57acc204d266274b98423,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,69c57acc204d266274b98424,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,69c57acc204d266274b98425,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,69c57acc204d266274b98426,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,69c57acc204d266274b98427,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,69c57acc204d266274b98428,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,69c57acc204d266274b98429,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,69c57acc204d266274b9842a,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,69c57acc204d266274b9842b,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,69c57acc204d266274b9842c,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,69c57acc204d266274b9842d,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
13,69c57acc204d266274b9842e,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
14,69c57acc204d266274b9842f,Rafael,Gato,Mia15,Banho,65,Ourinhos,2026-03-02,Cartão
15,69c57acc204d266274b98430,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
16,69c57acc204d266274b98431,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
17,69c57acc204d266274b98432,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
18,69c57acc204d266274b98433,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
19,69c57acc204d266274b98434,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
20,69c57acc204d266274b98435,Caio,Cachorro,Spike21,Banho,70,Ourinhos,2026-03-08,Dinheiro
21,69c57acc204d266274b98436,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
22,69c57acc204d266274b98437,Elisa,Cachorro,Mel23,Exame,210,Ourinhos,2026-03-10,Cartão
23,69c57acc204d266274b98438,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
24,69c57acc204d266274b98439,Gisele,Gato,Nina25,Vacinação,85,Ourinhos,2026-03-12,Dinheiro
25,69c57acc204d266274b9843a,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
26,69c57acc204d266274b9843b,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
27,69c57acc204d266274b9843c,Joao,Gato,Luna28,Banho,60,Pompeia,2026-03-02,Dinheiro
28,69c57acc204d266274b9843d,Karen,Cachorro,Thor29,Cirurgia,780,Pompeia,2026-03-03,Cartão
29,69c57acc204d266274b9843e,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
30,69c57acc204d266274b9843f,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
31,69c57acc204d266274b98440,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
32,69c57acc204d266274b98441,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
33,69c57acc204d266274b98442,Paulo,Cachorro,Bolt34,Banho,75,Pompeia,2026-03-08,Cartão
34,69c57acc204d266274b98443,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
35,69c57acc204d266274b98444,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
36,69c57acc204d266274b98445,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
37,69c57acc204d266274b98446,Tiago,Gato,Lili38,Vacinação,85,Pompeia,2026-03-12,Dinheiro
38,69c57acc204d266274b98447,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
39,69c57acc204d266274b98448,Vitor,Gato,Mia40,Banho,70,Marilia,2026-03-02,Cartão
40,69c57acc204d266274b98449,Wesley,Cachorro,Thor41,Cirurgia,870,Marilia,2026-03-03,Cartão
41,69c57acc204d266274b9844a,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
42,69c57acc204d266274b9844b,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
43,69c57acc204d266274b9844c,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
44,69c57acc204d266274b9844d,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
45,69c57acc204d266274b9844e,Bruna,Cachorro,Spike46,Banho,80,Marilia,2026-03-08,Dinheiro
46,69c57acc204d266274b9844f,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
47,69c57acc204d266274b98450,Dora,Cachorro,Mel48,Exame,220,Marilia,2026-03-10,Cartão
48,69c57acc204d266274b98451,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
49,69c57acc204d266274b98452,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

In [13]:
df_valores = pd.DataFrame(consulta_valor)

print(f"Total de atendimentos entre R$ 90 e R$ 200: {len(df_valores)}")
display(df_valores)

Total de atendimentos entre R$ 90 e R$ 200: 34

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69c57acc204d266274b98421,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69c57acc204d266274b98422,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69c57acc204d266274b98424,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
3,69c57acc204d266274b98425,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
4,69c57acc204d266274b98426,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
5,69c57acc204d266274b98427,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
6,69c57acc204d266274b9842a,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
7,69c57acc204d266274b9842b,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
8,69c57acc204d266274b9842c,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
9,69c57acc204d266274b9842d,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
10,69c57acc204d266274b9842e,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
11,69c57acc204d266274b98431,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
12,69c57acc204d266274b98432,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
13,69c57acc204d266274b98433,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
14,69c57acc204d266274b98434,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
15,69c57acc204d266274b98436,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
16,69c57acc204d266274b98438,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
17,69c57acc204d266274b9843a,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
18,69c57acc204d266274b9843b,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
19,69c57acc204d266274b9843e,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
20,69c57acc204d266274b9843f,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
21,69c57acc204d266274b98440,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
22,69c57acc204d266274b98441,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
23,69c57acc204d266274b98443,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
24,69c57acc204d266274b98444,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
25,69c57acc204d266274b98445,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
26,69c57acc204d266274b98447,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
27,69c57acc204d266274b9844a,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
28,69c57acc204d266274b9844b,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
29,69c57acc204d266274b9844c,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
30,69c57acc204d266274b9844d,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
31,69c57acc204d266274b9844f,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
32,69c57acc204d266274b98451,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
33,69c57acc204d266274b98452,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

In [14]:
df_cidades = pd.DataFrame(atendimentos_cidades)

print(f"Total de atendimentos nestas cidades: {len(df_cidades)}")
display(df_cidades)

Total de atendimentos nestas cidades: 38

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69c57acc204d266274b98421,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69c57acc204d266274b98422,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69c57acc204d266274b98423,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,69c57acc204d266274b98424,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,69c57acc204d266274b98425,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,69c57acc204d266274b98426,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,69c57acc204d266274b98427,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,69c57acc204d266274b98428,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,69c57acc204d266274b98429,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,69c57acc204d266274b9842a,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,69c57acc204d266274b9842b,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,69c57acc204d266274b9842c,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,69c57acc204d266274b9842d,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
13,69c57acc204d266274b9842e,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
14,69c57acc204d266274b9842f,Rafael,Gato,Mia15,Banho,65,Ourinhos,2026-03-02,Cartão
15,69c57acc204d266274b98430,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
16,69c57acc204d266274b98431,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
17,69c57acc204d266274b98432,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
18,69c57acc204d266274b98433,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
19,69c57acc204d266274b98434,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
20,69c57acc204d266274b98435,Caio,Cachorro,Spike21,Banho,70,Ourinhos,2026-03-08,Dinheiro
21,69c57acc204d266274b98436,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
22,69c57acc204d266274b98437,Elisa,Cachorro,Mel23,Exame,210,Ourinhos,2026-03-10,Cartão
23,69c57acc204d266274b98438,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
24,69c57acc204d266274b98439,Gisele,Gato,Nina25,Vacinação,85,Ourinhos,2026-03-12,Dinheiro
25,69c57acc204d266274b9843a,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
26,69c57acc204d266274b9843b,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
27,69c57acc204d266274b9843c,Joao,Gato,Luna28,Banho,60,Pompeia,2026-03-02,Dinheiro
28,69c57acc204d266274b9843d,Karen,Cachorro,Thor29,Cirurgia,780,Pompeia,2026-03-03,Cartão
29,69c57acc204d266274b9843e,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
30,69c57acc204d266274b9843f,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
31,69c57acc204d266274b98440,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
32,69c57acc204d266274b98441,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
33,69c57acc204d266274b98442,Paulo,Cachorro,Bolt34,Banho,75,Pompeia,2026-03-08,Cartão
34,69c57acc204d266274b98443,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
35,69c57acc204d266274b98444,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
36,69c57acc204d266274b98445,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
37,69c57acc204d266274b98446,Tiago,Gato,Lili38,Vacinação,85,Pompeia,2026-03-12,Dinheiro

5 - Verificar valores nulos

In [15]:
nulos = df.isnull().sum()

display(nulos)

_id                0
tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

6 - Calcular faturamento total

In [16]:
faturamento_total = df['valor'].sum()

print("Faturamento Total: R$", faturamento_total)

Faturamento Total: R$ 8895

7 - Faturamento por cidade.

In [17]:
faturamento_cidade = df.groupby('cidade')['valor'].sum().sort_values(ascending=False)
faturamento_cidade

cidade
Ourinhos    2380
Marilia     2275
Assis       2220
Pompeia     2020
Name: valor, dtype: int64

8 - Faturamento por serviço

In [18]:
faturamento_servico = df.groupby('servico')['valor'].sum().sort_values(ascending=False)
faturamento_servico

servico
Cirurgia     3370
Consulta     2655
Exame        1505
Vacinação     830
Banho         535
Name: valor, dtype: int64

9 - Ticket médio geral

In [19]:
ticket_medio = df['valor'].mean()

print(f"Ticket Médio Geral: R$ {ticket_medio:.2f}")

Ticket Médio Geral: R$ 177.90

10 - Ticket médio por cidade

In [20]:
ticket_medio_cidade = df.groupby('cidade')['valor'].mean()

print("Ticket Médio Por Cidade:")
display(ticket_medio_cidade)

Ticket Médio Por Cidade:

cidade
Assis       170.769231
Marilia     189.583333
Ourinhos    183.076923
Pompeia     168.333333
Name: valor, dtype: float64

11 - Serviço mais lucrativo

In [21]:
servico_mais_lucrativo = faturamento_servico.idxmax()
valor_mais_lucrativo = faturamento_servico.max()
print(f"Serviço mais lucrativo: {servico_mais_lucrativo} (R$ {valor_mais_lucrativo:.2f})")

Serviço mais lucrativo: Cirurgia (R$ 3370.00)

12 - Cidade com maior faturamento.

In [22]:
cidade_maior_faturamento = faturamento_cidade.idxmax()
valor_mais_lucrativo = faturamento_cidade.max()
print(f"Cidade com maior faturamento:{ cidade_maior_faturamento} (R$ {valor_mais_lucrativo:.2f})")

Cidade com maior faturamento:Ourinhos (R$ 2380.00)

14 - Tres maiores atendimentos.

In [23]:
tres_maiores_atendimentos = df.nlargest(3, 'valor')[['tutor', 'nome_pet', 'servico', 'valor', 'cidade']]
print(tres_maiores_atendimentos)

     tutor nome_pet   servico  valor    cidade
15   Sofia   Luna16  Cirurgia    900  Ourinhos
40  Wesley   Thor41  Cirurgia    870   Marilia
7   Helena     Mel8  Cirurgia    820     Assis

Relatório

In [24]:
relatorio = {
    "data_geracao" : datetime.now(),
    "faturamento_total": float(faturamento_total),
    "faturamento_cidade" : faturamento_cidade.to_dict(),
    "faturamento_servico" : faturamento_servico.to_dict(),  
    "ticket_medio": float(ticket_medio),                    
    "ticket_medio_cidade": ticket_medio_cidade.to_dict(),   
    "servico_mais_lucrativo": servico_mais_lucrativo,
    "cidade_maior_faturamento": cidade_maior_faturamento, 
    "tres_maiores_atendimentos": tres_maiores_atendimentos,
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 26, 18, 28, 29, 519649),
 'faturamento_total': 8895.0,
 'faturamento_cidade': {'Ourinhos': 2380,
  'Marilia': 2275,
  'Assis': 2220,
  'Pompeia': 2020},
 'faturamento_servico': {'Cirurgia': 3370,
  'Consulta': 2655,
  'Exame': 1505,
  'Vacinação': 830,
  'Banho': 535},
 'ticket_medio': 177.9,
 'ticket_medio_cidade': {'Assis': 170.76923076923077,
  'Marilia': 189.58333333333334,
  'Ourinhos': 183.07692307692307,
  'Pompeia': 168.33333333333334},
 'servico_mais_lucrativo': 'Cirurgia',
 'cidade_maior_faturamento': 'Ourinhos',
 'tres_maiores_atendimentos':      tutor nome_pet   servico  valor    cidade
 15   Sofia   Luna16  Cirurgia    900  Ourinhos
 40  Wesley   Thor41  Cirurgia    870   Marilia
 7   Helena     Mel8  Cirurgia    820     Assis}

In [25]:
colecao_relatorios = db['relatorios']

In [26]:
for r in colecao_relatorios.find():
    display(r)

In [28]:
print(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 26, 18, 28, 29, 519649), 'faturamento_total': 8895.0, 'faturamento_cidade': {'Ourinhos': 2380, 'Marilia': 2275, 'Assis': 2220, 'Pompeia': 2020}, 'faturamento_servico': {'Cirurgia': 3370, 'Consulta': 2655, 'Exame': 1505, 'Vacinação': 830, 'Banho': 535}, 'ticket_medio': 177.9, 'ticket_medio_cidade': {'Assis': 170.76923076923077, 'Marilia': 189.58333333333334, 'Ourinhos': 183.07692307692307, 'Pompeia': 168.33333333333334}, 'servico_mais_lucrativo': 'Cirurgia', 'cidade_maior_faturamento': 'Ourinhos', 'tres_maiores_atendimentos':      tutor nome_pet   servico  valor    cidade
15   Sofia   Luna16  Cirurgia    900  Ourinhos
40  Wesley   Thor41  Cirurgia    870   Marilia
7   Helena     Mel8  Cirurgia    820     Assis}